"""add task finished with status

Revision ID: 1df6f8396f8b
Revises: 535d7836d917
Create Date: 2018-11-15 20:57:46.198813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df6f8396f8b'
down_revision = '535d7836d917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_with_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'completed_with_status')
    # ### end Alembic commands ###
