"""tasks actualization

Revision ID: 6060cae70531
Revises: f34b00f3775f
Create Date: 2019-08-27 14:05:31.264132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6060cae70531'
down_revision = 'f34b00f3775f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'])
    op.drop_index('twitter_tag', table_name='user')
    op.drop_column('user', 'twitter_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('twitter_tag', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('twitter_tag', 'user', ['twitter_tag'], unique=True)
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'user_id')
    # ### end Alembic commands ###
