"""add user ip to task model

Revision ID: cf220943590c
Revises: 1df6f8396f8b
Create Date: 2019-05-27 18:56:04.218885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf220943590c'
down_revision = '1df6f8396f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_ip', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'user_ip')
    # ### end Alembic commands ###
