"""empty message

Revision ID: f34b00f3775f
Revises: 8e02c61b507c
Create Date: 2019-07-31 17:33:15.453794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34b00f3775f'
down_revision = '8e02c61b507c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('twitter_tag', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'user', ['twitter_tag'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'twitter_tag')
    # ### end Alembic commands ###
